readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\ip_tcb_before_3.b16"=0x00e7eafc
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\xnspe_before_3.b16"=0x01018d00
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\tcp_outflags_before_3.b16"=0x00a00066
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\tcp_stats_before_3.b16"=0x00e7f690
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\mfreeq_before_3.b16"=0x00e7f814 
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\FlowControlOff_before_3.b16"=0x00c06d24
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\tcp_header_mbuf_before_3.b16"=0x00facaf8
readfile,raw16,gui "E:\ViaTelecom\HC_Code\merge_code_from_Nicey\bin\tcp_mssopt_before_3.b16"=0x00c06d14
